# Plugins
gems:
- jekyll-sitemap
safe: true

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "Women Techmakers Istanbul 2015"
email: "wtm@gdgistanbul.com"
description: "Women Techmakers is a set of event about Women in technology"
baseurl: ""
url: "http://wtmistanbul.com/"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-58630743-1"
googleAnalyticsSiteUrl: "wtmistanbul.com"
siteVerification: "J78BVBOHc0PWM6qbrydtmvG1KjsM5HFF4JUSzcuoqCw"

# Organizer Info
organizerName: "GDG Women Istanbul"
organizerAlternateName: "Google Developer Group Istanbul"
organizerDescription: "Open and volunteer geek communities who create exciting projects and share experience about Google technology with passion."
organizerEmail: "wtm@gdgistanbul.com"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "http://www.gdgistanbul.com/"

# Head
metaKeywords: "wtm, women, womentechmakers, event, gdg, google, programming, android, chrome, developers, Istanbul"
twitterAccount: "@wtmistanbul"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
c4pUrl: ""
c4sponsorsUrl: ""


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/blog/", text: "Blog"}
 #- {permalink: "/schedule/", text: "Schedule"}
 #- {permalink: "/speakers/", text: "Speakers"}
 #- {permalink: "/team/", text: "Team"}
 - {permalink: "/logistics/", text: "Venue"}
 - {permalink: "/startup/", text: "Startup Launch"}
bottomNavigationLinks:
 - {link: "https://docs.google.com/forms/d/16AI23TnSQFg5yCqOIXeCj1hSlQvw1ihtx0XenZKfflk/viewform?usp=send_form", text: "Become a speaker"}
rightNavigationButtons:
 - {link: "https://docs.google.com/forms/d/16AI23TnSQFg5yCqOIXeCj1hSlQvw1ihtx0XenZKfflk/viewform?usp=send_form", text: "Become a speaker"}

# Hero Block
heroImage: "hero.jpg"
heroTitle: "WTM Istanbul 2015"
eventDate: "15 March, 2015"
typeoutTextValues: '"Women", "Techmakers", "Istanbul"'
typeoutFallback: "Season"
heroButtons:
 - {link: "https://docs.google.com/forms/d/16AI23TnSQFg5yCqOIXeCj1hSlQvw1ihtx0XenZKfflk/viewform?usp=send_form", text: "Become a speaker"}
 - {permalink: "http://wtmistanbul15.eventbrite.com", text: "Register"}

# About Block
aboutTitle: "About Women Techmakers"
aboutBlock:
 - {title: "Conference", image: "conference.jpg", text: "Supporting women in tech through the power of example." }
 - {title: "Workshops", image: "workshop.jpg", text: "High-tech workshops, hands-on experience, hacking and debugging. Delivered by top women in tech!" }
 - {title: "Discussion", image: "hackathon.jpg", text: "How can we close the gender gap in science, tech, engineering & mathematics? On-stage panel discussion with experts and leaders." }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "700", specialCharacter: "+", info: "attendees", detail: "men & women"}
 - {count: "52", specialCharacter: "+", info: "speakers", detail: "all of them are women except 1 Googler"}
 - {count: "4", specialCharacter: "", info: "parallel tracks", detail: "plus workshops"}

# Latest News Block
latestNewsTitle: "Latest news"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Rockstar speakers"
rockstarSpeakersButtonText: "See all speakers"

# Location Block
locationBlockTitle: "Location"
eventLocationName: "Bahcesehir University Besiktas Campus"
eventLocationLink: "http://maps.google.com/maps?ll=41.041994,29.009049&z=16&t=m&hl=en-US&gl=US&mapclient=embed&cid=8534833363515311385"
eventStreetAddress: "Ciragan Caddesi, Besiktas"
eventAddressLocality: "Istanbul"
eventAddressLocalityRegion: ""
eventPostalCode: ""
eventAddressCountry: "Turkey"
eventStartTime: "2015-03-15T09:00"
eventDoorTime: "09:00"
eventEndTime: "2015-03-15T17:30"
eventPlaceCoordinates: "41.041994, 29.009049"
mapCenterCoordinates: "41.041994, 29.009049"
mapMobileCenterCoordinates: "41.041994, 29.009049"

# Venue Block
venueBlockTitle: "Venue"
venueBigImage: "venue_0.jpg"
venueSmallImage1: "venue_1.jpg"
venueSmallImage2: "venue_2.jpg"
venueSmallImage3: "venue_3.jpg"
venueTitle: "Bahcesehir University Besiktas Campus"
venueFeatures: [""]

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "What's Up?"
twitterHashTag: "wtmistanbul"
twitterFeed: "http://www.gdgistanbul.com/tweetledee/favoritesjson.php?c=10&cache_interval=8000"

# Partners Block
organizersTitle: "Organizers"
partnersTitle: "Partners"
partnersC4sponsorsButton: "Become a sponsor"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Subscribe for updates"
subscribeAction: "http://gdgistanbul.us7.list-manage.com/subscribe/post?u=850f58b0963bc8227e3448ce6&amp;id=db62e82145"
subscribeInfo: "Registration will be open around end of February. Number of tickets are limited. Stay tuned!"

# Tickets Block
ticketsTitle: "Pricetable"
ticketsInfo: "Tickets grant access to all conference sections, coffee brakes, lunch and party. Accommodation is NOT included in the ticket price."
ticketsOffers:
 -
  name: "Early Bird"
  price: "350"
  priceCurrency: "UAH"
  ticketsNumber: "150"
  ribbon: "-5%"
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Buy Now"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2014-08-25T10:00"
  validThrough: "2014-09-30T23:59"
 -
  name: "Last Chance"
  price: "450"
  priceCurrency: "UAH"
  ticketsNumber: "100"
  ribbon: "-20%"
  featured: true
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Buy Now"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2014-10-01T00:00"
  validThrough: "2014-10-23T23:59"
  disabled: true
 -
  name: "Student"
  price: "200"
  priceCurrency: "UAH"
  ticketsNumber: "50"
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Buy Now"
  additionalInfo: "Requires a valid student ID at the conference check in. Without student ID at the check in, ticket will be cancelled without refund"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2014-08-20T10:00"
  validThrough: "2014-10-23T23:59"
  soldOut: true
  soldOutText: "Sold Out"

# Footer
socialLinks:
 - {link: "https://plus.googleapis.com/communities/108925709024625495301", icon: "google-plus"}
 - {link: "https://twitter.com/intent/user?screen_name=wtmistanbul", icon: "twitter"}
 - {link: "https://www.facebook.com/pages/Women-Techmakers-Istanbul/671948679589644", icon: "facebook"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "http://www.gdgistanbul.com", text: "GDG Istanbul"}
   - {link: "https://developers.google.com", text: "Google Developers"}
 -
  title: "Contacts"
  links:
   - {link: "mailto:wtm@gdgistanbul.com", text: "wtm@gdgistanbul.com"}
 -
  title: "FAQ"
  links:
   - {permalink: "/cod/", text: "Code of Conduct"}

# Blog
blogTitle: "Latest news"
blogCommentsEnabled: true
discusShortName: "wtmistanbul"

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "About us"
aboutUs: "Google's services have become synonymous with simple things online. Number of technological innovations and IT industries in which Google is creating new products is enormous. It's hard to get to know all of them, but realistic. This is why people have started to gather in small local groups and share their experience. Later, the following groups have been called Google Developer Groups. GDGs can take many forms -- from just a few people getting together to watch some videos, to large gatherings with demos, tech talks, hackathons and conferences."

# Logistics Find Way Block
findWayTitle: "Find your way here"
findWayDistance: "Distance"
findWayDriving: "DRIVING"
findWayWalking: "WALKING"
findWayBicycling: "BICYCLING"
findWayTransit: "TRANSIT"
findWayFindFlight: "Find Flight"
logisticsMapCenterCoordinates: "41.041994, 29.009049"
logisticsMapMobileCenterCoordinates: "41.041994, 29.009049"

# Logistics Direction Details Block
directionDetailsImage: "direction-details.jpg"
directionDetailsTitle: "Get around Istanbul"
directionDetailsCards:
 - {title: "From the Airport", information: 'Airport is easily reachable by public transport. You can either take subway train or look for busses called "HAVATAŞ". More information is available at <a href="http://www.ataturkairport.com/en-EN/Transportation/pages/airporttrasnportation.aspx">airport website</a>.'}
 - {title: "Public Transit", information: 'You can either take subway train or look for busses called "HAVATAŞ". More information will be provided here to directly go to the venue.'}
 - {title: "Hotels", information: 'Istanbul has lots of great hotels and hostels. More information will be available later.'}
directionDetailsWideCards:
 -
  title: "Questions?"
  subCards:
   -
    title: "Hotels"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   -
    title: "Registration"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   -
    title: "Attendance Details"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}

# Hackathon
hackathonTitle: "Startup Launch"
enableHackathon: false

# Hackathon About Block
aboutHackathonTitle: "at Women Techmakers Istanbul"
hackathonRows:
 - {details: "You have the chance to be on the stage, pitch your idea to successful founders & VCs, get feedbacks, attend networking party at Women Techmakers Istanbul Conference. <br/><a href='http://www.gdgistanbul.com/2015/02/women-techmakers-istanbul-konferans-bu.html'> (Click here for Turkish)</a> <br/>Attendees will join to how to make a winning pitch session to improve/prepare their pitch sentences. <br/>And we will have some surprises for you. <br/>What will you get by attending? <br/>-Attend a winner elevator pitch workshop <br/>-Learn and practice to sell your business idea <br/>-Introduce yourself to the VCs <br/>-Meet with successful entrepreneurs <br/>-Networking with other entrepreneurs"}
 - {title: "Program", details: "How to make a winning elevator workshop (1 hour)<br/>One Sentence Elevator Pitches - 2 min. / each (1 hour)<br/>Feedbacks (1 hour)<br/>Network & Cocktail (1 hour)"}

# Hackathon Judges Block
judgesImage: "judges.jpg"
judgesTitle: "Judges"

# Hackathon Prizes Block
prizesTitle: "Prizes"
prizes:
 - {title: "2nd Place", image: "prize-2.png", info: "Amazing Moto 360"}
 - {title: "1nd Place", image: "prize-1.png", info: "Nexus 5 with pre-installed Android L"}
 - {title: "3nd Place", image: "prize-3.png", info: "Useful Chromecast"}

# Hackathon Location Block
hackathonLocationBlockTitle: "Location"
hackathonLocationName: "Communa"
hackathonLocationLink: "http://communa.net.ua/"
hackathonStreetAddress: "1 Halytska St"
hackathonAddressLocality: "Istanbul"
hackathonAddressLocalityRegion: "Istanbul"
hackathonPostalCode: "79000"
hackathonAddressCountry: "Turkey"
hackathonTimeTitle: "Hack through"
hackathonStartTime: "2014-10-24T10:00"
hackathonDoorTime: "09:00"
hackathonEndTime: "2014-10-25T00:00"
viewOnMap: "View on Google Maps"
hackathonPlaceCoordinates: "49.840999, 24.031144"
hackathonMapCenterCoordinates: "49.840696, 24.028754"
hackathonMapMobileCenterCoordinates: "49.841639, 24.031182"
